#!/usr/bin/env python3
"""Generate linter-specific config artifacts from the shared YAML file."""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
CONFIG_MODULE_DIR = REPO_ROOT / ".config" / "python"
if str(CONFIG_MODULE_DIR) not in sys.path:
    sys.path.insert(0, str(CONFIG_MODULE_DIR))

from config import LintConfig, load_config  # type: ignore  # noqa: E402

FLAKE8_PATH = REPO_ROOT / ".flake8"
PYLINTRC_PATH = REPO_ROOT / ".pylintrc"
PYCODESTYLE_PATH = REPO_ROOT / ".pycodestyle"
PYRIGHT_PATH = REPO_ROOT / "pyrightconfig.json"
CONFIG_DIR = REPO_ROOT / ".config" / "python" / "lint"
ROOTS_YAML_PATH = CONFIG_DIR / "roots.yaml"
EXCLUDES_YAML_PATH = CONFIG_DIR / "excludes.yaml"
CONFIG_DIR.mkdir(parents=True, exist_ok=True)
HEADER = "# Generated by tools/python/lint/sync_configs.py. Do not edit manually.\n"
DEFAULT_PYLINT_IGNORE = ("venv", ".venv", "build", "dist")


def _format_csv(values: tuple[str, ...]) -> str:
    return ",".join(values)


def _format_yaml_sequence(key: str, values: tuple[str, ...]) -> str:
    lines = [f"{key}:"]
    for value in values:
        escaped = value.replace("'", "''")
        lines.append(f"  - '{escaped}'")
    return "\n".join(lines)


def write_flake8(config: LintConfig) -> None:
    lines = [
        "[flake8]",
        f"max-line-length = {config.line_length}",
    ]
    if config.flake8.extend_ignore:
        lines.append(f"extend-ignore = {_format_csv(config.flake8.extend_ignore)}")
    if config.flake8.exclude:
        lines.append(f"exclude = {_format_csv(config.flake8.exclude)}")
    body = HEADER + "\n".join(lines) + "\n"
    FLAKE8_PATH.write_text(body, encoding="utf-8")


def write_pylintrc(config: LintConfig) -> None:
    ignore_paths = tuple(dict.fromkeys(DEFAULT_PYLINT_IGNORE + config.pylint.ignore))
    lines = ["[MASTER]", f"ignore = {_format_csv(ignore_paths)}"]
    if config.pylint.ignore_paths:
        lines.append(f"ignore-paths = {_format_csv(config.pylint.ignore_paths)}")
    if config.pylint.ignore_patterns:
        lines.append(f"ignore-patterns = {_format_csv(config.pylint.ignore_patterns)}")
    lines.append("extension-pkg-allow-list =")
    lines.append("")
    lines.append("[MESSAGES CONTROL]")
    if config.pylint.disable:
        lines.append(f"disable = {_format_csv(config.pylint.disable)}")
    lines.append("")
    lines.append("[FORMAT]")
    lines.append(f"max-line-length = {config.line_length}")
    body = HEADER + "\n".join(lines) + "\n"
    PYLINTRC_PATH.write_text(body, encoding="utf-8")


def write_pyright(config: LintConfig) -> None:
    payload = {"exclude": list(config.pyright.exclude)}
    PYRIGHT_PATH.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def write_pycodestyle(config: LintConfig) -> None:
    lines = ["[pycodestyle]", f"max-line-length = {config.line_length}"]
    if config.pycodestyle.ignore:
        lines.append(f"ignore = {_format_csv(config.pycodestyle.ignore)}")
    body = HEADER + "\n".join(lines) + "\n"
    PYCODESTYLE_PATH.write_text(body, encoding="utf-8")


def write_roots_yaml(config: LintConfig) -> None:
    data = _format_yaml_sequence("lint_roots", config.runner.auto_targets)
    ROOTS_YAML_PATH.write_text(HEADER + data + "\n", encoding="utf-8")


def write_excludes_yaml(config: LintConfig) -> None:
    data = _format_yaml_sequence("excludes", config.vendor_globs)
    EXCLUDES_YAML_PATH.write_text(HEADER + data + "\n", encoding="utf-8")


def main() -> None:
    config = load_config()
    write_flake8(config)
    write_pylintrc(config)
    write_pycodestyle(config)
    write_pyright(config)
    write_roots_yaml(config)
    write_excludes_yaml(config)


if __name__ == "__main__":
    main()
