#!/usr/bin/env python3
"""Generate lint configuration files from .config/python-lint.yaml."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict

try:
    import yaml  # type: ignore
except ImportError:  # pragma: no cover
    yaml = None  # type: ignore


REPO_ROOT = Path(__file__).resolve().parents[2]
CONFIG_PATH = REPO_ROOT / ".config" / "python-lint.yaml"
FLAKE8_PATH = REPO_ROOT / ".flake8"
PYLINTRC_PATH = REPO_ROOT / ".pylintrc"
HEADER = "# Generated by tools/python-lint/sync_configs.py. Do not edit manually.\n"


def _load_config() -> Dict[str, Any]:
    """Load the unified lint configuration from the repo-level YAML/JSON file."""
    raw = CONFIG_PATH.read_text(encoding="utf-8")
    if yaml is not None:
        return yaml.safe_load(raw)
    return json.loads(raw)


def _format_csv(values: list[str]) -> str:
    """Join a list of strings as a comma separated value used by linters."""
    return ",".join(values)


def write_flake8(config: Dict[str, Any]) -> None:
    """Write the generated .flake8 file based on the unified configuration."""
    line_length = config.get("line_length", 100)
    extend_ignore = config.get("flake8", {}).get("extend_ignore", [])
    body = (
        f"[flake8]\n"
        f"max-line-length = {line_length}\n"
        f"extend-ignore = {_format_csv(extend_ignore)}\n"
    )
    FLAKE8_PATH.write_text(HEADER + body, encoding="utf-8")


def write_pylintrc(config: Dict[str, Any]) -> None:
    """Write the generated .pylintrc file based on the unified configuration."""
    line_length = config.get("line_length", 100)
    disable = config.get("pylint", {}).get("disable", [])
    body = (
        "[MASTER]\n"
        "ignore = venv, .venv, build, dist\n"
        "extension-pkg-allow-list =\n\n"
        "[MESSAGES CONTROL]\n"
        f"disable = {_format_csv(disable)}\n\n"
        "[FORMAT]\n"
        f"max-line-length = {line_length}\n"
    )
    PYLINTRC_PATH.write_text(HEADER + body, encoding="utf-8")


def main() -> None:
    """Entry point that syncs the linter-specific files from the shared config."""
    if not CONFIG_PATH.exists():
        raise SystemExit(f"Missing config file: {CONFIG_PATH}")
    config = _load_config()
    write_flake8(config)
    write_pylintrc(config)


if __name__ == "__main__":
    main()
