#!/usr/bin/env python3
"""Generate linter-specific config artifacts from the shared YAML file."""

from __future__ import annotations

import json
import sys
from pathlib import Path

THIS_DIR = Path(__file__).resolve().parent
if str(THIS_DIR) not in sys.path:
    sys.path.insert(0, str(THIS_DIR))

from lint_config import LintConfig, load_config  # type: ignore  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[2]
FLAKE8_PATH = REPO_ROOT / ".flake8"
PYLINTRC_PATH = REPO_ROOT / ".pylintrc"
PYRIGHT_PATH = REPO_ROOT / "pyrightconfig.json"
HEADER = "# Generated by tools/python-lint/sync_configs.py. Do not edit manually.\n"
DEFAULT_PYLINT_IGNORE = ("venv", ".venv", "build", "dist")


def _format_csv(values: tuple[str, ...]) -> str:
    return ",".join(values)


def write_flake8(config: LintConfig) -> None:
    lines = [
        "[flake8]",
        f"max-line-length = {config.line_length}",
    ]
    if config.flake8.extend_ignore:
        lines.append(f"extend-ignore = {_format_csv(config.flake8.extend_ignore)}")
    if config.flake8.exclude:
        lines.append(f"exclude = {_format_csv(config.flake8.exclude)}")
    body = HEADER + "\n".join(lines) + "\n"
    FLAKE8_PATH.write_text(body, encoding="utf-8")


def write_pylintrc(config: LintConfig) -> None:
    ignore_paths = tuple(dict.fromkeys(DEFAULT_PYLINT_IGNORE + config.pylint.ignore))
    lines = ["[MASTER]", f"ignore = {_format_csv(ignore_paths)}"]
    if config.pylint.ignore_paths:
        lines.append(f"ignore-paths = {_format_csv(config.pylint.ignore_paths)}")
    lines.append("extension-pkg-allow-list =")
    lines.append("")
    lines.append("[MESSAGES CONTROL]")
    if config.pylint.disable:
        lines.append(f"disable = {_format_csv(config.pylint.disable)}")
    lines.append("")
    lines.append("[FORMAT]")
    lines.append(f"max-line-length = {config.line_length}")
    body = HEADER + "\n".join(lines) + "\n"
    PYLINTRC_PATH.write_text(body, encoding="utf-8")


def write_pyright(config: LintConfig) -> None:
    payload = {"exclude": list(config.pyright.exclude)}
    PYRIGHT_PATH.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def main() -> None:
    config = load_config()
    write_flake8(config)
    write_pylintrc(config)
    write_pyright(config)


if __name__ == "__main__":
    main()
