#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Manage the self-hosted GitHub Actions runner in the Docker stack.

.DESCRIPTION
    This script manages the GitHub Actions self-hosted runner including:
    - Creating required Docker volumes
    - Starting/stopping the runner service
    - Viewing runner logs
    - Registering/deregistering the runner

.PARAMETER Action
    The action to perform: setup, start, stop, restart, logs, status, cleanup

.PARAMETER Token
    GitHub Personal Access Token with repo and workflow permissions

.PARAMETER Repository
    GitHub repository in format owner/repo (default: DeanLuus22021994/Aspire-Full)

.EXAMPLE
    ./manage-runner.ps1 -Action setup -Token "ghp_xxxx"

.EXAMPLE
    ./manage-runner.ps1 -Action start

.EXAMPLE
    ./manage-runner.ps1 -Action logs -Follow
#>

param(
    [Parameter(Mandatory = $true)]
    [ValidateSet('setup', 'start', 'stop', 'restart', 'logs', 'status', 'cleanup', 'volumes')]
    [string]$Action,

    [Parameter(Mandatory = $false)]
    [string]$Token,

    [Parameter(Mandatory = $false)]
    [string]$Repository = "DeanLuus22021994/Aspire-Full",

    [Parameter(Mandatory = $false)]
    [switch]$Follow
)

$ErrorActionPreference = "Stop"

# Configuration
$ComposeFile = Join-Path $PSScriptRoot ".." ".devcontainer" "docker-compose.yml"
$EnvFile = Join-Path $PSScriptRoot ".." ".devcontainer" ".env"

# All required named volumes
$RequiredVolumes = @(
    # Development container volumes
    "aspire-nuget-cache",
    "aspire-dotnet-tools",
    "aspire-aspire-cli",
    "aspire-vscode-extensions",
    "aspire-workspace",
    "aspire-dashboard-data",
    "aspire-docker-data",
    "aspire-docker-certs",
    # GitHub Actions Runner volumes
    "aspire-runner-data",
    "aspire-runner-work",
    "aspire-runner-nuget",
    "aspire-runner-npm",
    "aspire-runner-toolcache",
    # Database volumes
    "aspire-postgres-data",
    "aspire-redis-data"
)

# Network
$RequiredNetwork = "aspire-network"

function Write-Info { param([string]$Message) Write-Host "[INFO] $Message" -ForegroundColor Green }
function Write-Warn { param([string]$Message) Write-Host "[WARN] $Message" -ForegroundColor Yellow }
function Write-Err { param([string]$Message) Write-Host "[ERROR] $Message" -ForegroundColor Red }

function Test-DockerRunning {
    try {
        docker info 2>&1 | Out-Null
        return $true
    }
    catch {
        return $false
    }
}

function New-DockerVolumes {
    Write-Info "Creating Docker volumes..."

    foreach ($volume in $RequiredVolumes) {
        $exists = docker volume ls -q --filter "name=^${volume}$" 2>$null
        if (-not $exists) {
            Write-Info "Creating volume: $volume"
            docker volume create $volume
        }
        else {
            Write-Info "Volume exists: $volume"
        }
    }
}

function New-DockerNetwork {
    Write-Info "Creating Docker network..."

    $exists = docker network ls -q --filter "name=^${RequiredNetwork}$" 2>$null
    if (-not $exists) {
        Write-Info "Creating network: $RequiredNetwork"
        docker network create $RequiredNetwork
    }
    else {
        Write-Info "Network exists: $RequiredNetwork"
    }
}

function Set-RunnerEnvironment {
    param([string]$GithubToken, [string]$Repo)

    Write-Info "Configuring runner environment..."

    $envContent = @"
# GitHub Actions Runner Configuration
# Generated by manage-runner.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

GITHUB_TOKEN=$GithubToken
GITHUB_REPOSITORY=$Repo
RUNNER_NAME=aspire-runner
RUNNER_LABELS=self-hosted,Linux,X64,docker,dotnet,aspire
RUNNER_GROUP=Default
"@

    Set-Content -Path $EnvFile -Value $envContent -Force
    Write-Info "Environment file created: $EnvFile"
    Write-Warn "Keep this file secure - it contains your GitHub token!"
}

function Start-RunnerService {
    Write-Info "Starting GitHub Actions runner..."

    Push-Location (Split-Path $ComposeFile -Parent)
    try {
        docker compose up -d github-runner
        Write-Info "Runner service started"
    }
    finally {
        Pop-Location
    }
}

function Stop-RunnerService {
    Write-Info "Stopping GitHub Actions runner..."

    Push-Location (Split-Path $ComposeFile -Parent)
    try {
        docker compose stop github-runner
        Write-Info "Runner service stopped"
    }
    finally {
        Pop-Location
    }
}

function Get-RunnerStatus {
    Write-Info "Checking runner status..."

    Push-Location (Split-Path $ComposeFile -Parent)
    try {
        docker compose ps github-runner
    }
    finally {
        Pop-Location
    }
}

function Get-RunnerLogs {
    param([switch]$FollowLogs)

    Write-Info "Fetching runner logs..."

    Push-Location (Split-Path $ComposeFile -Parent)
    try {
        if ($FollowLogs) {
            docker compose logs -f github-runner
        }
        else {
            docker compose logs --tail 100 github-runner
        }
    }
    finally {
        Pop-Location
    }
}

function Remove-RunnerResources {
    Write-Info "Cleaning up runner resources..."

    Push-Location (Split-Path $ComposeFile -Parent)
    try {
        # Stop and remove the runner container
        docker compose rm -sf github-runner

        Write-Warn "Runner volumes are preserved. To remove them, run:"
        Write-Host "  docker volume rm aspire-runner-data aspire-runner-work aspire-runner-nuget aspire-runner-npm aspire-runner-toolcache"
    }
    finally {
        Pop-Location
    }
}

function Show-VolumeStatus {
    Write-Info "Docker volume status:"
    Write-Host ""

    foreach ($volume in $RequiredVolumes) {
        $exists = docker volume ls -q --filter "name=^${volume}$" 2>$null
        if ($exists) {
            Write-Host "  [✓] $volume" -ForegroundColor Green
        }
        else {
            Write-Host "  [✗] $volume (not created)" -ForegroundColor Red
        }
    }

    Write-Host ""
    Write-Info "Docker network status:"
    $networkExists = docker network ls -q --filter "name=^${RequiredNetwork}$" 2>$null
    if ($networkExists) {
        Write-Host "  [✓] $RequiredNetwork" -ForegroundColor Green
    }
    else {
        Write-Host "  [✗] $RequiredNetwork (not created)" -ForegroundColor Red
    }
}

# Main execution
if (-not (Test-DockerRunning)) {
    Write-Err "Docker is not running. Please start Docker Desktop first."
    exit 1
}

switch ($Action) {
    "setup" {
        if (-not $Token) {
            Write-Err "GitHub Token is required for setup. Use -Token parameter."
            Write-Host ""
            Write-Host "To create a token:"
            Write-Host "  1. Go to https://github.com/settings/tokens/new"
            Write-Host "  2. Select scopes: repo, workflow, admin:org (for org runners)"
            Write-Host "  3. Generate and copy the token"
            exit 1
        }

        New-DockerVolumes
        New-DockerNetwork
        Set-RunnerEnvironment -GithubToken $Token -Repo $Repository
        Start-RunnerService

        Write-Host ""
        Write-Info "Setup complete! The runner should now appear in your repository settings."
        Write-Host "  Go to: https://github.com/$Repository/settings/actions/runners"
    }

    "start" {
        if (-not (Test-Path $EnvFile)) {
            Write-Err "Runner not configured. Run setup first: ./manage-runner.ps1 -Action setup -Token <your-token>"
            exit 1
        }
        Start-RunnerService
    }

    "stop" {
        Stop-RunnerService
    }

    "restart" {
        Stop-RunnerService
        Start-RunnerService
    }

    "logs" {
        Get-RunnerLogs -FollowLogs:$Follow
    }

    "status" {
        Get-RunnerStatus
    }

    "cleanup" {
        Remove-RunnerResources
    }

    "volumes" {
        Show-VolumeStatus
    }
}
