#!/usr/bin/env python3
"""Generate pytest config artifacts from the shared YAML file."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from types import ModuleType
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[3]
CONFIG_MODULE_PATH = REPO_ROOT / ".config" / "config.py"
PYTEST_INI_PATH = REPO_ROOT / "pytest.ini"
CONFIG_DIR = REPO_ROOT / ".config" / "python" / "test"
ROOTS_YAML_PATH = CONFIG_DIR / "roots.yaml"
EXCLUDES_YAML_PATH = CONFIG_DIR / "excludes.yaml"
CONFIG_DIR.mkdir(parents=True, exist_ok=True)
HEADER = "# Generated by tools/python/test/sync_configs.py. Do not edit manually.\n"


def _load_config_module() -> ModuleType:
    """Load the .config/config.py module."""
    spec = importlib.util.spec_from_file_location(
        "workspace_dotconfig", CONFIG_MODULE_PATH
    )
    if spec is None or spec.loader is None:
        raise RuntimeError("Unable to load .config/config.py module")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


CONFIG_MODULE = _load_config_module()
TestConfigType = Any
load_test_config = getattr(CONFIG_MODULE, "load_test_config")


def _format_yaml_sequence(key: str, values: tuple[str, ...]) -> str:
    """Format a sequence of strings as a YAML list."""
    lines = [f"{key}:"]
    for value in values:
        escaped = value.replace("'", "''")
        lines.append(f"  - '{escaped}'")
    return "\n".join(lines)


def write_pytest_ini(config: TestConfigType) -> None:
    """Write the pytest.ini file."""
    lines: list[str] = ["[pytest]"]
    if config.pytest.addopts:
        lines.append(f"addopts = {' '.join(config.pytest.addopts)}")
    if config.pytest.markers:
        lines.append("markers =")
        lines.extend([f"    {marker}" for marker in config.pytest.markers])
    if config.pytest.filterwarnings:
        lines.append("filterwarnings =")
        lines.extend([f"    {fw}" for fw in config.pytest.filterwarnings])
    PYTEST_INI_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_roots_yaml(config: TestConfigType) -> None:
    """Write the roots.yaml file."""
    data = _format_yaml_sequence("test_roots", config.runner.auto_targets)
    ROOTS_YAML_PATH.write_text(HEADER + data + "\n", encoding="utf-8")


def write_excludes_yaml(config: TestConfigType) -> None:
    """Write the excludes.yaml file."""
    data = _format_yaml_sequence("excludes", config.vendor_globs)
    EXCLUDES_YAML_PATH.write_text(HEADER + data + "\n", encoding="utf-8")


def main() -> None:
    config = load_test_config()
    write_pytest_ini(config)
    write_roots_yaml(config)
    write_excludes_yaml(config)


if __name__ == "__main__":
    main()
