# Stage 1: Build Native Library
FROM base-native AS build
WORKDIR /src

# Copy Native Project
COPY ["Aspire-Full.Native/", "Aspire-Full.Native/"]

# Build Native Library
WORKDIR /src/Aspire-Full.Native
RUN mkdir -p build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CUDA_FLAGS="-MD" && \
    make

# Stage 2: Export
FROM scratch AS export
COPY --from=build /src/Aspire-Full.Native/build/libAspireFullNative.so /
